
spring:
  application:
    name: microservice-gateway

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: "optional:nacos:${spring.application.name}.yml"

  # Nacos 服务发现与配置中心
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}
      config:
        server-addr: ${NACOS_SERVER_ADDR:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        file-extension: yaml
        username: ${NACOS_USERNAME:nacos}
        password: ${NACOS_PASSWORD:nacos}

server:
  port: ${GATEWAY_PORT:8080}

logging:
  file:
    path: logs/microservice-gateway
